    MODULE OPERATORS

    USE SURFACE_MODULE



    CONTAINS


    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!   OCTREE_DXX
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    SUBROUTINE OCTREE_DXX(POINT,        V)
    TYPE(POINTPHI), POINTER :: POINT
    REAL(8) :: LEFTS
    REAL(8) :: RIGHTS
    REAL(8) :: V
    real(8) :: temp1

    IF(.NOT. ASSOCIATED(POINT)) THEN
        V=0.0
        RETURN
    END IF

    IF(.NOT. ASSOCIATED(POINT%LEFT) .OR. .NOT. ASSOCIATED(POINT%RIGHT) ) THEN
        V=0.0
        RETURN
    ENDIF
temp1 = point%x
    LEFTS = POINT%X - POINT%LEFT%X
    RIGHTS = POINT%RIGHT%X-POINT%X

    V = (POINT%RIGHT%PHI - POINT%PHI) / RIGHTS * 2.0/(LEFTS + RIGHTS) - (POINT%PHI - POINT%LEFT%PHI)/LEFTS * 2.0/(LEFTS + RIGHTS)

    END SUBROUTINE




    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!   OCTREE_DXPLUS
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    SUBROUTINE OCTREE_DXPLUS(POINT,         V)
    TYPE(POINTPHI), POINTER :: POINT
    REAL(8) :: RIGHTS
    REAL(8) :: V
    REAL(8) :: V1
    REAL(8) :: V2
    REAL(8) :: V3

    IF (.NOT. ASSOCIATED(POINT) ) THEN
        V=0.0
        RETURN
    END IF

    IF ( .NOT. ASSOCIATED(POINT%RIGHT) ) THEN
        V=0.0
        RETURN
    END IF

    RIGHTS = POINT%RIGHT%X - POINT%X
    CALL OCTREE_DXX(POINT, V1)
    CALL OCTREE_DXX(POINT%RIGHT, V2)
    CALL MINMOD(V1, V2, V3)
    V = (POINT%RIGHT%PHI - POINT%PHI)/RIGHTS - RIGHTS/2.0 * V3

    END SUBROUTINE



    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!   OCTREE_DXMINUS
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    SUBROUTINE OCTREE_DXMINUS(POINT,        V)
    TYPE(POINTPHI), POINTER :: POINT
    REAL(8) :: LEFTS
    REAL(8) :: V
    REAL(8) :: V1
    REAL(8) :: V2
    REAL(8) :: V3

    IF (.NOT. ASSOCIATED(POINT)) THEN
        V=0.0
        RETURN
    END IF

    IF(.NOT. ASSOCIATED(POINT%LEFT)) THEN
        V=0.0
        RETURN
    END IF

    CALL OCTREE_DXX(POINT, V1)
    CALL OCTREE_DXX(POINT%LEFT, V2)
    CALL MINMOD(V1, V2, V3)

    LEFTS = POINT%X - POINT%LEFT%X
    V = (POINT%PHI - POINT%LEFT%PHI)/LEFTS + LEFTS/2.0 * V3

    END SUBROUTINE


    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!   OCTREE_DX
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    SUBROUTINE OCTREE_DX(POINT,         V)
    TYPE(POINTPHI), POINTER :: POINT
    REAL(8) :: LEFTS
    REAL(8) :: RIGHTS
    REAL(8) :: V

    IF ( .NOT. ASSOCIATED(POINT%LEFT) ) THEN
        CALL OCTREE_DXPLUS(POINT, V)
        RETURN
    END IF

    IF ( .NOT. ASSOCIATED(POINT%RIGHT) ) THEN
        CALL OCTREE_DXMINUS(POINT, V)
        RETURN
    END IF

    LEFTS = POINT%X - POINT%LEFT%X
    RIGHTS = POINT%RIGHT%X - POINT%X
    V = (POINT%RIGHT%PHI - POINT%PHI)/RIGHTS * LEFTS/(LEFTS + RIGHTS) +(POINT%PHI - POINT%LEFT%PHI)/LEFTS * RIGHTS/(LEFTS + RIGHTS)

    END SUBROUTINE


    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!   OCTREE_DYY
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    SUBROUTINE OCTREE_DYY(POINT,        V)
    TYPE(POINTPHI), POINTER :: POINT
    REAL(8) :: BOTTOMS
    REAL(8) :: TOPS
    REAL(8) :: V
    IF(.NOT. ASSOCIATED(POINT)) THEN
        V=0.0
        RETURN
    END IF

    IF(.NOT. ASSOCIATED(POINT%BOTTOM) .OR. .NOT. ASSOCIATED(POINT%TOP) ) THEN
        V=0.0
        RETURN
    ENDIF

    BOTTOMS = POINT%Y - POINT%BOTTOM%Y
    TOPS = POINT%TOP%Y - POINT%Y
    V = (POINT%TOP%PHI - POINT%PHI)/TOPS * 2.0/(BOTTOMS + TOPS) -	(POINT%PHI - POINT%BOTTOM%PHI)/BOTTOMS * 2./(BOTTOMS + TOPS)

    END SUBROUTINE


    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!   OCTREE_DYPLUS
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    SUBROUTINE OCTREE_DYPLUS(POINT,         V)
    TYPE(POINTPHI), POINTER :: POINT
    REAL(8) :: BOTTOMS
    REAL(8) :: TOPS
    REAL(8) :: V
    REAL(8) :: V1
    REAL(8) :: V2
    REAL(8) :: V3

    IF(.NOT. ASSOCIATED(POINT)) THEN
        V=0.0
        RETURN
    END IF

    IF(.NOT. ASSOCIATED(POINT%TOP)) THEN
        V=0.0
        RETURN
    END IF

    TOPS = POINT%TOP%Y - POINT%Y
    CALL OCTREE_DYY(POINT, V1)
    CALL OCTREE_DYY(POINT%TOP, V2)
    CALL MINMOD(V1, V2, V3)

    V= (POINT%TOP%PHI - POINT%PHI)/TOPS	- TOPS/2.0 * V3
    END SUBROUTINE


    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!   OCTREE_DYMINUS
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    SUBROUTINE OCTREE_DYMINUS(POINT,         V)
    TYPE(POINTPHI), POINTER :: POINT
    REAL(8) :: BOTTOMS
    REAL(8) :: V
    REAL(8) :: V1
    REAL(8) :: V2
    REAL(8) :: V3

    IF (.NOT. ASSOCIATED(POINT)) THEN
        V=0.0
        RETURN
    END IF

    IF(.NOT. ASSOCIATED(POINT%BOTTOM)) THEN
        V=0.0
        RETURN
    END IF

    CALL OCTREE_DYY(POINT, V1)
    CALL OCTREE_DYY(POINT%BOTTOM, V2)
    CALL MINMOD(V1, V2, V3)

    BOTTOMS = POINT%Y - POINT%BOTTOM%Y
    V = (POINT%PHI - POINT%BOTTOM%PHI)/BOTTOMS + BOTTOMS/2. * V3

    END SUBROUTINE

    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!   OCTREE_DY
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    SUBROUTINE OCTREE_DY(POINT,      V)
    TYPE(POINTPHI), POINTER :: POINT
    REAL(8) :: BOTTOMS
    REAL(8) :: TOPS
    REAL(8) :: V

    IF ( .NOT. ASSOCIATED(POINT%BOTTOM) ) THEN
        CALL OCTREE_DYPLUS(POINT, V)
        RETURN
    END IF

    IF ( .NOT. ASSOCIATED(POINT%TOP) ) THEN
        CALL OCTREE_DYMINUS(POINT, V)
        RETURN
    END IF

    BOTTOMS = POINT%Y - POINT%BOTTOM%Y
    TOPS = POINT%TOP%Y - POINT%Y
    V= (POINT%TOP%PHI - POINT%PHI)/TOPS * BOTTOMS/(BOTTOMS + TOPS) +	(POINT%PHI - POINT%BOTTOM%PHI)/BOTTOMS * TOPS/(BOTTOMS + TOPS)
    END SUBROUTINE



    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!   OCTREE_DZZ
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    SUBROUTINE OCTREE_DZZ(POINT,        V)

    TYPE(POINTPHI), POINTER :: POINT
    REAL(8) :: BACKS
    REAL(8) :: FRONTS
    REAL(8) :: V
    IF(.NOT. ASSOCIATED(POINT)) THEN
        V=0.0
        RETURN
    END IF

    IF(.NOT. ASSOCIATED(POINT%BACK) .OR. .NOT. ASSOCIATED(POINT%FRONT) ) THEN
        V=0.0
        RETURN
    ENDIF

    BACKS = POINT%Z - POINT%BACK%Z
    FRONTS = POINT%FRONT%Z-POINT%Z

    V = (POINT%FRONT%PHI - POINT%PHI) / FRONTS * 2.0/(BACKS + FRONTS) - (POINT%PHI - POINT%BACK%PHI)/BACKS * 2.0/(BACKS + FRONTS)

    END SUBROUTINE




    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!   OCTREE_DZPLUS
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    SUBROUTINE OCTREE_DZPLUS(POINT,      V)

    TYPE(POINTPHI), POINTER :: POINT
    REAL(8) :: FRONTS
    REAL(8) :: V
    REAL(8) :: V1
    REAL(8) :: V2
    REAL(8) :: V3

    IF (.NOT. ASSOCIATED(POINT) ) THEN
        V=0.0
        RETURN
    END IF

    IF ( .NOT. ASSOCIATED(POINT%FRONT) ) THEN
        V=0.0
        RETURN
    END IF

    FRONTS = POINT%FRONT%Z - POINT%Z
    CALL OCTREE_DZZ(POINT, V1)
    CALL OCTREE_DZZ(POINT%FRONT, V2)
    CALL MINMOD(V1, V2, V3)
    V = (POINT%FRONT%PHI - POINT%PHI)/FRONTS - FRONTS/2.0 * V3

    END SUBROUTINE



    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!   OCTREE_DZMINUS
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    SUBROUTINE OCTREE_DZMINUS(POINT,        V)
    TYPE(POINTPHI), POINTER :: POINT
    REAL(8) :: BACKS
    REAL(8) :: V
    REAL(8) :: V1
    REAL(8) :: V2
    REAL(8) :: V3

    IF (.NOT. ASSOCIATED(POINT)) THEN
        V=0.0
        RETURN
    END IF

    IF(.NOT. ASSOCIATED(POINT%BACK)) THEN
        V=0.0
        RETURN
    END IF

    CALL OCTREE_DZZ(POINT, V1)
    CALL OCTREE_DZZ(POINT%BACK, V2)
    CALL MINMOD(V1, V2, V3)

    BACKS = POINT%Z - POINT%BACK%Z
    V = (POINT%PHI - POINT%BACK%PHI)/BACKS + BACKS/2.0 * V3

    END SUBROUTINE


    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!   OCTREE_DZ
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    SUBROUTINE OCTREE_DZ(POINT,         V)
    TYPE(POINTPHI), POINTER :: POINT
    REAL(8) :: BACKS
    REAL(8) :: FRONTS
    REAL(8) :: V

    IF ( .NOT. ASSOCIATED(POINT%BACK) ) THEN
        CALL OCTREE_DZPLUS(POINT, V)
        RETURN
    END IF

    IF ( .NOT. ASSOCIATED(POINT%FRONT) ) THEN
        CALL OCTREE_DZMINUS(POINT, V)
        RETURN
    END IF

    BACKS = POINT%Z - POINT%BACK%Z
    FRONTS = POINT%FRONT%Z - POINT%Z
    V = (POINT%FRONT%PHI - POINT%PHI)/FRONTS * BACKS/(BACKS + FRONTS) +(POINT%PHI - POINT%BACK%PHI)/BACKS * FRONTS/(BACKS + FRONTS)

    END SUBROUTINE




    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!   OCTREE_DXY
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    SUBROUTINE OCTREE_DXY(POINT,        V)

    TYPE(POINTPHI), POINTER :: POINT
    REAL(8) :: DELTA
    REAL(8) :: V

    IF(.NOT. ASSOCIATED(POINT)) THEN
        V=0.0
        RETURN
    END IF

    DELTA = POINT%X - POINT%LEFT%X

    V =  (POINT%RIGHT%TOP%PHI - POINT%RIGHT%BOTTOM%PHI - POINT%LEFT%TOP%PHI + POINT%LEFT%BOTTOM%PHI)/(4.*DELTA*DELTA)

    END SUBROUTINE


    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!   OCTREE_DXZ
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    SUBROUTINE OCTREE_DXZ(POINT,        V)

    TYPE(POINTPHI), POINTER :: POINT
    REAL(8) :: DELTA
    REAL(8) :: V

    IF(.NOT. ASSOCIATED(POINT)) THEN
        V=0.0
        RETURN
    END IF

    DELTA = POINT%X - POINT%LEFT%X

    V =  (POINT%RIGHT%FRONT%PHI - POINT%RIGHT%BACK%PHI - POINT%LEFT%FRONT%PHI + POINT%LEFT%BACK%PHI)/(4.*DELTA*DELTA)

    END SUBROUTINE


    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!   OCTREE_DYZ
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    SUBROUTINE OCTREE_DYZ(POINT,        V)

    TYPE(POINTPHI), POINTER :: POINT
    REAL(8) :: DELTA
    REAL(8) :: V

    IF(.NOT. ASSOCIATED(POINT)) THEN
        V=0.0
        RETURN
    END IF

    DELTA = POINT%Y - POINT%LEFT%Y

    V =  (POINT%TOP%FRONT%PHI - POINT%TOP%BACK%PHI - POINT%BOTTOM%FRONT%PHI + POINT%BOTTOM%BACK%PHI)/(4.*DELTA*DELTA)

    END SUBROUTINE



    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!   OCTREE_MEANCURV
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    SUBROUTINE OCTREE_MEANCURV(POINT,       V)

    TYPE(POINTPHI), POINTER :: POINT
    REAL(8) :: V
    REAL(8) :: DXX
    REAL(8) :: DYY
    REAL(8) :: DZZ

    CALL OCTREE_DXX(POINT,DXX) 
    CALL OCTREE_DYY(POINT, DYY) 
    CALL OCTREE_DZZ(POINT, DZZ)

    V = DXX + DYY + DZZ

    END SUBROUTINE


    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!   OCTREE_CURVATURE
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    SUBROUTINE OCTREE_CURVATURE(POINT,      V)

    TYPE(POINTPHI), POINTER :: POINT
    REAL(8) :: V
    REAL(8) :: DX
    REAL(8) :: DY
    REAL(8) :: DZ
    REAL(8) :: DXX
    REAL(8) :: DYY
    REAL(8) :: DZZ
    REAL(8) :: DXY
    REAL(8) :: DXZ
    REAL(8) :: DYZ

    REAL(8) :: PROJ(3,3)
    REAL(8) :: HESSIAN(3,3)

    REAL(8) :: MTX(3,3)
    INTEGER :: I
    INTEGER :: J
    INTEGER :: K

    REAL(8) :: ALPHA
    REAL(8) :: BETA
    REAL(8) :: D
    REAL(8) :: K1
    REAL(8) :: K2

    CALL OCTREE_DX(POINT, DX)
    CALL OCTREE_DY(POINT, DY)
    CALL OCTREE_DZ(POINT, DZ)

    CALL OCTREE_DXX(POINT, DXX)
    CALL OCTREE_DYY(POINT, DYY)
    CALL OCTREE_DZZ(POINT, DZZ)
    CALL OCTREE_DXY(POINT, DXY)
    CALL OCTREE_DXZ(POINT, DXZ)
    CALL OCTREE_DYZ(POINT, DYZ)

    PROJ(1,1) = 1.0-DX*DX
    PROJ(2,2) = 1.0-DY*DY
    PROJ(3,3) = 1.0-DZ*DZ
    PROJ(1,2) = -DX*DY
    PROJ(2,1) = -DX*DY
    PROJ(1,3) = -DX*DZ
    PROJ(3,1) = -DX*DZ
    PROJ(2,3) = -DY*DZ
    PROJ(3,2) = -DY*DZ

    HESSIAN(1,1) = DXX
    HESSIAN(2,2) = DYY
    HESSIAN(3,3) = DZZ
    HESSIAN(1,2) = DXY
    HESSIAN(2,1) = DXY
    HESSIAN(1,3) = DXZ
    HESSIAN(3,1) = DXZ
    HESSIAN(2,3) = DYZ
    HESSIAN(3,2) = DYZ

    DO I=1,3
        DO J=1,3
            MTX(I,J) = 0
            DO K=1,3
                MTX(I,J) = MTX(I,J) + PROJ(I,K)*HESSIAN(K,J)
            END DO
        END DO
    END DO

    ALPHA = MTX(1,1) + MTX(2,2) + MTX(3,3)
    BETA = MTX(1,1)*MTX(2,2) + MTX(1,1)*MTX(3,3) + MTX(2,2)*MTX(3,3) - MTX(1,2)*MTX(2,1) - MTX(1,3)*MTX(3,1) - MTX(2,3)*MTX(3,2)

    D = ALPHA*ALPHA-4.*BETA

    K1 = (ALPHA + SQRT(MAX(D,0.0)))/2.0
    K2 = (ALPHA - SQRT(MAX(D,0.0)))/2.0

    V = ABS(K1) + ABS(K2)

    END SUBROUTINE


    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!   OCTREE_WENO
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    SUBROUTINE OCTREE_WENO(POINT,I, DELTA,      V)

    TYPE(POINTPHI), POINTER :: POINT
    REAL(8) :: V

    INTEGER :: I
    REAL(8) :: DELTA

    REAL(8) :: W

    REAL(8) :: V1
    REAL(8) :: V2
    REAL(8) :: V3
    REAL(8) :: V4
    REAL(8) :: V5

    REAL(8) :: S1
    REAL(8) :: S2
    REAL(8) :: S3
    REAL(8) :: EPS
    REAL(8) :: A1
    REAL(8) :: A2
    REAL(8) :: A3
    REAL(8) :: W1
    REAL(8) :: W2
    REAL(8) :: W3

    IF(I==0) THEN
        IF(.NOT. ASSOCIATED(POINT%RIGHT) .OR. ABS(POINT%RIGHT%X - POINT%X - DELTA) > MINERROR .OR. .NOT. ASSOCIATED( POINT%RIGHT%RIGHT) .OR. ABS(POINT%RIGHT%RIGHT%X - POINT%RIGHT%X - DELTA) > MINERROR .OR. .NOT. ASSOCIATED(POINT%RIGHT%RIGHT%RIGHT) .OR. ABS(POINT%RIGHT%RIGHT%RIGHT%X - POINT%RIGHT%RIGHT%X - DELTA) > MINERROR .OR. .NOT. ASSOCIATED(POINT%LEFT) .OR. ABS(POINT%X - POINT%LEFT%X - DELTA) > MINERROR .OR. .NOT. ASSOCIATED(POINT%LEFT%LEFT) .OR. ABS(POINT%LEFT%X - POINT%LEFT%LEFT%X - DELTA) > MINERROR) THEN 
            CALL OCTREE_DXPLUS(POINT,V)
            return
        ENDIF


        V1 = (POINT%RIGHT%RIGHT%RIGHT%PHI - POINT%RIGHT%RIGHT%PHI)/DELTA
        V2 = (POINT%RIGHT%RIGHT%PHI - POINT%RIGHT%PHI)/DELTA
        V3 = (POINT%RIGHT%PHI - POINT%PHI)/DELTA

        V4 = (POINT%PHI - POINT%LEFT%PHI)/DELTA
        V5 = (POINT%LEFT%PHI - POINT%LEFT%LEFT%PHI)/DELTA
    ELSE IF(I==1) THEN
        IF(.NOT. ASSOCIATED(POINT%LEFT) .OR. ABS(POINT%X - POINT%LEFT%X - DELTA) > MINERROR .OR. .NOT. ASSOCIATED(POINT%LEFT%LEFT) .OR.	ABS(POINT%LEFT%X - POINT%LEFT%LEFT%X - DELTA) > MINERROR .OR. .NOT. ASSOCIATED(POINT%LEFT%LEFT%LEFT) .OR.	ABS(POINT%LEFT%LEFT%X - POINT%LEFT%LEFT%LEFT%X - DELTA) > MINERROR .OR.	.NOT. ASSOCIATED(POINT%RIGHT) .OR. ABS(POINT%RIGHT%X - POINT%X - DELTA) > MINERROR .OR. .NOT. ASSOCIATED(POINT%RIGHT%RIGHT) .OR. ABS(POINT%RIGHT%RIGHT%X - POINT%RIGHT%X - DELTA) > MINERROR) THEN 
            CALL OCTREE_DXMINUS(POINT,v)
            return
        ENDIF
        V1 = (POINT%LEFT%LEFT%PHI - POINT%LEFT%LEFT%LEFT%PHI)/DELTA
        V2 = (POINT%LEFT%PHI - POINT%LEFT%LEFT%PHI)/DELTA
        V3 = (POINT%PHI - POINT%LEFT%PHI)/DELTA
        V4 = (POINT%RIGHT%PHI - POINT%PHI)/DELTA
        V5 = (POINT%RIGHT%RIGHT%PHI - POINT%RIGHT%PHI)/DELTA
    ELSE IF(I==2) THEN
        IF(.NOT. ASSOCIATED(POINT%TOP) .OR. ABS(POINT%TOP%Y - POINT%Y - DELTA) > MINERROR .OR. .NOT. ASSOCIATED(POINT%TOP%TOP) .OR. ABS(POINT%TOP%TOP%Y - POINT%TOP%Y - DELTA) > MINERROR .OR. .NOT. ASSOCIATED(POINT%TOP%TOP%TOP) .OR. ABS(POINT%TOP%TOP%TOP%Y - POINT%TOP%TOP%Y - DELTA) > MINERROR .OR. .NOT. ASSOCIATED(POINT%BOTTOM ) .OR. ABS(POINT%Y - POINT%BOTTOM%Y - DELTA) > MINERROR .OR. .NOT. ASSOCIATED(POINT%BOTTOM%BOTTOM ) .OR. ABS(POINT%BOTTOM%Y - POINT%BOTTOM%BOTTOM%Y - DELTA) > MINERROR) THEN
            CALL OCTREE_DYPLUS(POINT,v)
            return
        END IF
        V1 = (POINT%TOP%TOP%TOP%PHI - POINT%TOP%TOP%PHI)/DELTA
        V2 = (POINT%TOP%TOP%PHI - POINT%TOP%PHI)/DELTA
        V3 = (POINT%TOP%PHI - POINT%PHI)/DELTA
        V4 = (POINT%PHI - POINT%BOTTOM%PHI)/DELTA
        V5 = (POINT%BOTTOM%PHI - POINT%BOTTOM%BOTTOM%PHI)/DELTA
    ELSE IF(I==3) THEN
        IF(.NOT. ASSOCIATED(POINT%BOTTOM) .OR. ABS(POINT%Y - POINT%BOTTOM%Y - DELTA) > MINERROR .OR. .NOT. ASSOCIATED(POINT%BOTTOM%BOTTOM ) .OR. ABS(POINT%BOTTOM%Y - POINT%BOTTOM%BOTTOM%Y - DELTA) > MINERROR .OR. .NOT. ASSOCIATED(POINT%BOTTOM%BOTTOM%BOTTOM).OR. ABS(POINT%BOTTOM%BOTTOM%Y - POINT%BOTTOM%BOTTOM%BOTTOM%Y - DELTA) > MINERROR .OR. .NOT. ASSOCIATED(POINT%TOP) .OR. ABS(POINT%TOP%Y - POINT%Y - DELTA) > MINERROR .OR. .NOT. ASSOCIATED(POINT%TOP%TOP) .OR. ABS(POINT%TOP%TOP%Y - POINT%TOP%Y - DELTA) > MINERROR) THEN
            CALL OCTREE_DYMINUS(POINT,v)
            return
        ENDIF
        V1 = (POINT%BOTTOM%BOTTOM%PHI - POINT%BOTTOM%BOTTOM%BOTTOM%PHI)/DELTA
        V2 = (POINT%BOTTOM%PHI - POINT%BOTTOM%BOTTOM%PHI)/DELTA
        V3 = (POINT%PHI - POINT%BOTTOM%PHI)/DELTA
        V4 = (POINT%TOP%PHI - POINT%PHI)/DELTA
        V5 = (POINT%TOP%TOP%PHI - POINT%TOP%PHI)/DELTA
    ELSE IF(I==4) THEN
        IF(.NOT. ASSOCIATED(POINT%FRONT).OR. ABS(POINT%FRONT%Z - POINT%Z - DELTA) > MINERROR .OR. .NOT. ASSOCIATED(POINT%FRONT%FRONT) .OR. ABS(POINT%FRONT%FRONT%Z - POINT%FRONT%Z - DELTA) > MINERROR .OR. .NOT. ASSOCIATED(POINT%FRONT%FRONT%FRONT) .OR. ABS(POINT%FRONT%FRONT%FRONT%Z - POINT%FRONT%FRONT%Z - DELTA) > MINERROR .OR. .NOT. ASSOCIATED(POINT%BACK) .OR. ABS(POINT%Z - POINT%BACK%Z - DELTA) > MINERROR .OR. .NOT. ASSOCIATED(POINT%BACK%BACK) .OR. ABS(POINT%BACK%Z - POINT%BACK%BACK%Z - DELTA) > MINERROR) THEN
            CALL OCTREE_DZPLUS(POINT,v)
            return
        END IF
        V1 = (POINT%FRONT%FRONT%FRONT%PHI - POINT%FRONT%FRONT%PHI)/DELTA
        V2 = (POINT%FRONT%FRONT%PHI - POINT%FRONT%PHI)/DELTA
        V3 = (POINT%FRONT%PHI - POINT%PHI)/DELTA
        V4 = (POINT%PHI - POINT%BACK%PHI)/DELTA
        V5 = (POINT%BACK%PHI - POINT%BACK%BACK%PHI)/DELTA
    ELSE IF (I==5) THEN 
        IF(.NOT. ASSOCIATED(POINT%BACK) .OR. ABS(POINT%Z - POINT%BACK%Z - DELTA) > MINERROR .OR. .NOT. ASSOCIATED(POINT%BACK%BACK) .OR. ABS(POINT%BACK%Z - POINT%BACK%BACK%Z - DELTA) > MINERROR .OR. .NOT. ASSOCIATED(POINT%BACK%BACK%BACK) .OR. ABS(POINT%BACK%BACK%Z - POINT%BACK%BACK%BACK%Z - DELTA) > MINERROR .OR. .NOT. ASSOCIATED(POINT%FRONT) .OR. ABS(POINT%FRONT%Z - POINT%Z - DELTA) > MINERROR .OR. .NOT. ASSOCIATED(POINT%FRONT%FRONT) .OR. ABS(POINT%FRONT%FRONT%Z - POINT%FRONT%Z - DELTA) > MINERROR) THEN
            CALL OCTREE_DZMINUS(POINT,v)
            return
        END IF
        V1 = (POINT%BACK%BACK%PHI - POINT%BACK%BACK%BACK%PHI)/DELTA
        V2 = (POINT%BACK%PHI - POINT%BACK%BACK%PHI)/DELTA
        V3 = (POINT%PHI - POINT%BACK%PHI)/DELTA
        V4 = (POINT%FRONT%PHI - POINT%PHI)/DELTA
        V5 = (POINT%FRONT%FRONT%PHI - POINT%FRONT%PHI)/DELTA
    ENDIF

    S1 = 13./12. * (V1-2.*V2+V3)*(V1-2.*V2+V3) + 1./4. * (V1-4.*V2+3.*V3)*(V1-4.*V2+3.*V3)
    S2 = 13./12. * (V2-2.*V3+V4)*(V2-2.*V3+V4) + 1./4. * (V2-V4)*(V2-V4)
    S3 = 13./12. * (V3-2.*V4+V5)*(V3-2.*V4+V5) + 1./4. * (3.*V3-4.*V4+V5)*(3.*V3-4.*V4+V5)

    EPS = 1E-6

    A1 = 1./10. * 1./((EPS+S1)*(EPS+S1))
    A2 = 6./10. * 1./((EPS+S2)*(EPS+S2))
    A3 = 3./10. * 1./((EPS+S3)*(EPS+S3))

    W1 = A1/(A1+A2+A3)
    W2 = A2/(A1+A2+A3)
    W3 = A3/(A1+A2+A3)

    V = W1*(V1/3.-7.*V2/6.+11.*V3/6.) + W2*(-V2/6.+5.*V3/6.+V4/3.) + W3*(V3/3.+5.*V4/6.-V5/6.)

    END SUBROUTINE


    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !!!   COMPUTEPHI
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    SUBROUTINE COMPUTEPHI(CURRENT, X, Y, Z,        V)


    TYPE(OCTREE), POINTER :: CURRENT
    REAL(8) :: X,Y,Z

    REAL(8) :: V

    REAL(8) :: X1
    REAL(8) :: X2
    REAL(8) :: Y1
    REAL(8) :: Y2
    REAL(8) :: Z1
    REAL(8) :: Z2
    REAL(8) :: L

    REAL(8) :: V1
    REAL(8) :: V2
    REAL(8) :: V3

    REAL(8) :: PHIXX
    REAL(8) :: PHIYY
    REAL(8) :: PHIZZ

    REAL(8) :: TEMPTEMP


    X1 = CURRENT%PHI_LEFTBOTTOMBACK%X
    X2 = CURRENT%PHI_RIGHTBOTTOMBACK%X
    Y1 = CURRENT%PHI_LEFTBOTTOMBACK%Y
    Y2 = CURRENT%PHI_LEFTTOPBACK%Y
    Z1 = CURRENT%PHI_LEFTBOTTOMBACK%Z
    Z2 = CURRENT%PHI_LEFTBOTTOMFRONT%Z
    L = CURRENT%LENGTH

    CALL OCTREE_DXX(CURRENT%PHI_LEFTBOTTOMBACK, V1)
    PHIXX = ABS(V1)
    CALL OCTREE_DXX(CURRENT%PHI_RIGHTBOTTOMBACK, V1)
    PHIXX = MIN(PHIXX, ABS(V1))
    CALL OCTREE_DXX(CURRENT%PHI_LEFTTOPBACK, V1)
    PHIXX = MIN(PHIXX, ABS(V1))
    CALL OCTREE_DXX(CURRENT%PHI_RIGHTTOPBACK,V1)
    PHIXX = MIN(PHIXX, ABS(V1))
    CALL OCTREE_DXX(CURRENT%PHI_LEFTBOTTOMFRONT, V1)
    PHIXX = MIN(PHIXX, ABS(V1))
    CALL OCTREE_DXX(CURRENT%PHI_RIGHTBOTTOMFRONT,V1)
    PHIXX = MIN(PHIXX, ABS(V1))
    CALL OCTREE_DXX(CURRENT%PHI_LEFTTOPFRONT,V1)
    PHIXX = MIN(PHIXX, ABS(V1))
    CALL OCTREE_DXX(CURRENT%PHI_RIGHTTOPFRONT, V1)
    PHIXX = MIN(PHIXX, ABS(V1))

    CALL OCTREE_DYY(CURRENT%PHI_LEFTBOTTOMBACK, V2)
    PHIYY = ABS(V2)
    CALL OCTREE_DYY(CURRENT%PHI_RIGHTBOTTOMBACK,V2)
    PHIYY = MIN(PHIYY, ABS(V2))
    CALL OCTREE_DYY(CURRENT%PHI_LEFTTOPBACK,V2)
    PHIYY = MIN(PHIYY, ABS(V3))
    CALL OCTREE_DYY(CURRENT%PHI_RIGHTTOPBACK,V2)
    PHIYY = MIN(PHIYY, ABS(V3))
    CALL OCTREE_DYY(CURRENT%PHI_LEFTBOTTOMFRONT, V2)
    PHIYY = MIN(PHIYY, ABS(V2))
    CALL OCTREE_DYY(CURRENT%PHI_RIGHTBOTTOMFRONT, V2)
    PHIYY = MIN(PHIYY, ABS(V2))
    CALL OCTREE_DYY(CURRENT%PHI_LEFTTOPFRONT,V2)
    PHIYY = MIN(PHIYY, ABS(V2))
    CALL OCTREE_DYY(CURRENT%PHI_RIGHTTOPFRONT,V2)
    PHIYY = MIN(PHIYY, ABS(V2))


    CALL OCTREE_DZZ(CURRENT%PHI_LEFTBOTTOMBACK, V3)
    PHIZZ = ABS(V3)
    CALL OCTREE_DZZ(CURRENT%PHI_RIGHTBOTTOMBACK, V3)
    PHIZZ = MIN(PHIZZ, ABS(V3))
    CALL OCTREE_DZZ(CURRENT%PHI_LEFTTOPBACK, V3)
    PHIZZ = MIN(PHIZZ, ABS(V3))
    CALL OCTREE_DZZ(CURRENT%PHI_RIGHTTOPBACK, V3)
    PHIZZ = MIN(PHIZZ, ABS(V3))
    CALL OCTREE_DZZ(CURRENT%PHI_LEFTBOTTOMFRONT, V3)
    PHIZZ = MIN(PHIZZ, ABS(V3))
    CALL OCTREE_DZZ(CURRENT%PHI_RIGHTBOTTOMFRONT, V3)
    PHIZZ = MIN(PHIZZ, ABS(V3))
    CALL OCTREE_DZZ(CURRENT%PHI_LEFTTOPFRONT, V3)
    PHIZZ = MIN(PHIZZ, ABS(V3))
    CALL     OCTREE_DZZ(CURRENT%PHI_RIGHTTOPFRONT, V3)
    PHIZZ = MIN(PHIZZ, ABS(V3))

    V = CURRENT%PHI_LEFTBOTTOMBACK%PHI*(X2-X)/L*(Y2-Y)/L*(Z2-Z)/L + CURRENT%PHI_LEFTTOPBACK%PHI*(X2-X)/L*(Y-Y1)/L*(Z2-Z)/L &
    + CURRENT%PHI_RIGHTBOTTOMBACK%PHI*(X-X1)/L*(Y2-Y)/L*(Z2-Z)/L + CURRENT%PHI_RIGHTTOPBACK%PHI*(X-X1)/L*(Y-Y1)/L*(Z2-Z)/L &
    + CURRENT%PHI_LEFTBOTTOMFRONT%PHI*(X2-X)/L*(Y2-Y)/L*(Z-Z1)/L + CURRENT%PHI_LEFTTOPFRONT%PHI*(X2-X)/L*(Y-Y1)/L*(Z-Z1)/L &
    + CURRENT%PHI_RIGHTBOTTOMFRONT%PHI*(X-X1)/L*(Y2-Y)/L*(Z-Z1)/L + CURRENT%PHI_RIGHTTOPFRONT%PHI*(X-X1)/L*(Y-Y1)/L*(Z-Z1)/L
    !- PHIXX*(X-X1)*(X2-X)/2. - PHIYY*(Y-Y1)*(Y2-Y)/2. - PHIZZ*(Z-Z1)*(Z2-Z)/2.

    END SUBROUTINE



    END MODULE